name: MERN CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node --version

      - run: docker --version

      - run: ls

      - run: npm ci
        working-directory: ./backend

      - run: npm ci
        working-directory: ./frontend

      - run: npm test
        working-directory: ./backend

      - run: npm test -- --watchAll=false
        working-directory: ./frontend

      - run: npm run build
        working-directory: ./frontend

      - run: docker build -t mern-backend ./backend

      - run: docker build -t mern-frontend ./frontend
