name: MERN CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: node --version

      - run: docker --version

      - run: ls

      - run: npm ci
        working-directory: ./backend

      - run: npm ci
        working-directory: ./frontend

      - run: npm test
        working-directory: ./backend

      - run: npm test -- --watchAll=false
        working-directory: ./frontend

      - run: npm run build
        working-directory: ./frontend

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: docker build -t sykes9/mern-backend:${{ github.sha }} -f ./backend/Dockerfile.prod ./backend

      - run: docker build -t sykes9/mern-frontend:${{ github.sha }} -f ./frontend/Dockerfile.prod ./frontend

      - run: docker push sykes9/mern-backend:${{ github.sha }}

      - run: docker push sykes9/mern-frontend:${{ github.sha }}
